/* Generated by bin2c, do not edit manually */
#ifndef __src_res_binary_emuscv32x32xrgba8888_data_h_included
#define __src_res_binary_emuscv32x32xrgba8888_data_h_included

/* Contents of file src/res/emuscv32x32xrgba8888.data */
extern const long int src_res_emuscv32x32xrgba8888_data_size;
extern const unsigned char src_res_emuscv32x32xrgba8888_data[4096];

#endif    /* __src_res_binary_emuscv32x32xrgba8888_data_h_included */
